language: php
php:
    - 5.6
    - 7.0

matrix:
    include:
        - php: 5.6
          env: dependencies="--prefer-lowest --prefer-stable"

script:
    - vendor/bin/tester tests -s -p php -c tests/php-unix.ini

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - composer install --no-interaction --dev --prefer-source

cache:
    directories:
        - $HOME/.composer/cache
